# Generated by Django 5.0.6 on 2024-05-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('salary', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('client_name', models.CharField(max_length=200)),
                ('guests', models.IntegerField(blank=True, null=True)),
                ('employees', models.ManyToManyField(blank=True, related_name='events', to='events.employee')),
            ],
        ),
    ]
